include:
  - project: 'tcw-group/technology/platform-engineering/development-operations/cicd-configurations'
    ref: 'time-non-protected-test'
    file: '/time-next/pipelines/x1/time-next.application.cloud.default.pipeline.yml'

variables:
  PROJECT_NAME: time-next
  ENABLE_TLS: 'true'
  DOMAIN: time
  DEPLOYMENT_NAME: time-next

  ## AKS Tags ####################################################################################
  APPLICATION_OWNER: 'engineering-solutions'
  APPLICATION_TYPE: 'time-next-monorepo'
  APPLICATION_SENSITIVITY: 'private'
  ################################################################################################
  
