include:
  - project: 'tcw-group/technology/platform-engineering/development-operations/cicd-configurations'
    ref: 'main'
    file: '/html/pipelines/x1/react.application.cloud.default.pipeline.yml'

variables:
  PROJECT_NAME: time-next
  DOMAIN: time-next
  DEPLOYMENT_NAME: TIME-Next

  ## AKS Tags ####################################################################################
  APPLICATION_OWNER: 'engineering-solutions'
  APPLICATION_TYPE: 'time-next-monorepo'
  APPLICATION_SENSITIVITY: 'private'
  ################################################################################################