###################################################################################################
## Pipeline for react application utilizing the external dockerfile and the platform
## engineering umbrella helm chart
## Last Updated: 2/11/2025
## Released: 2/11/2025
###################################################################################################
image: node:20

include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - project: 'tcw-group/technology/platform-engineering/development-operations/cicd-configurations'
    ref: 'main'
    file:
      - '/html/templates/react/x1/react.install.template.yml'
      - '/html/templates/react/x1/react.lint.template.yml'
      - '/html/templates/react/x1/react.test.template.yml'
      - '/html/templates/react/x1/react.version.template.yml'
      - '/html/templates/react/x1/react.build.template.yml'
      - '/html/templates/react/x1/react.dry-run.template.yml'
      - '/html/templates/react/x1/react.release.template.yml'
      - '/html/templates/react/x1/react.package.template.yml'
      - '/html/templates/react/x1/react.upgrade.template.yml'
      - '/html/templates/react/x1/react.tag.template.yml'
      - '/html/templates/react/x1/react.variables.format.yml' 

stages:
  - install
  - validation
  - build
  - sandbox
  - dry-run
  - development
  - qa
  - test
  - uat
  - integration
  - production
  - performance

workflow:
  rules:
  - if: $CI_COMMIT_TAG
    when: never
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: never
  - when: always

cache: 
  key: ${CI_COMMIT_REF_SLUG}
  paths: 
    - node_modules/

variables:
  PROJECT_NAME: unknown-project-name
  DEPLOYMENT_NAME: unknown-deployment-name

  ## AKS Tags ####################################################################################
  APPLICATION_OWNER: 'application-owner-not-set'
  APPLICATION_TYPE: 'application-type-not-set'
  APPLICATION_SENSITIVITY: 'application-sensitivity-not-set'
  ################################################################################################
  
  ## Environments ################################################################################
  ENABLE_SANDBOX: 'true'
  ENABLE_DEV: 'true'
  ENABLE_QA: 'true'
  ENABLE_TEST: 'false'
  ENABLE_UAT: 'false'
  ENABLE_INT: 'false'
  ENABLE_PROD: 'true'
  ENABLE_PERF: 'false'
  ################################################################################################

  ## DNS Configurations ###########################################################################
  ENABLE_TLS: 'false'
  DOMAIN: unknown-domain
  #################################################################################################
 
  ## Security Configurations #####################################################################
  GITLAB_ADVANCED_SAST_ENABLED: 'true'
  #################################################################################################

  ## Docker Configurations ########################################################################
  OVERRIDE_DOCKER: 'false'
  DEFAULT_DOCKER_SOURCE_REF: 'main'
  DEFAULT_DOCKER_SOURCE_PATH: 'react/alpine/v1'
  DEFAULT_DOCKER_SOURCE_FILE: 'dockerfile.cicd'
  #################################################################################################

install:
  stage: install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull-push
  extends: .install

lint:
  stage: validation
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull
  extends: .lint
  allow_failure: true

test:
  stage: validation
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull
  extends: .test
  allow_failure: true

sast:
  stage: validation

dependency_scanning:
  stage: validation

secret_detection:
  stage: validation
  variables:
    SECRET_DETECTION_EXCLUDED_PATHS: 'node_modules'
    SECURE_LOG_LEVEL: 'debug'
    SECRET_DETECTION_HISTORIC_SCAN: 'true'

build-sandbox:
  stage: sandbox
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
  variables:
    TARGET_ENV: sandbox
    TARGET_OUTPUT: apps/platform-shell/dist
  before_script:
    - export NODE_OPTIONS="--max-old-space-size=8192"
  script:
    - npm run build:$TARGET_ENV
  artifacts:
    paths:
      - $CI_PROJECT_DIR/$TARGET_OUTPUT
  allow_failure: true
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH != 'main' && $ENABLE_SANDBOX == "true"

package-sandbox:
  stage: sandbox
  needs:
    - job: build-sandbox
      artifacts: true
  extends: .package
  variables:
    TARGET_ENV: sandbox
    TARGET_OUTPUT: apps/platform-shell/dist
    DOCKER_SOURCE_REF: $DEFAULT_DOCKER_SOURCE_REF
    DOCKER_SOURCE_PATH: $DEFAULT_DOCKER_SOURCE_PATH
    DOCKER_SOURCE_FILE: $DEFAULT_DOCKER_SOURCE_FILE
  rules:
    - if: $CI_COMMIT_BRANCH != 'main' && $ENABLE_SANDBOX == "true"


dry-run-sandbox:
  stage: sandbox
  extends: .react-dry-run
  needs:
    - job: package-sandbox
  variables:
    TARGET_ENV: sandbox
    TARGET_NAMESPACE: sandbox
    TARGET_HOSTNAME: $DOMAIN-sandbox.np.tcw.com
  rules:
    - if: $CI_COMMIT_BRANCH != 'main' && $ENABLE_SANDBOX == "true"

deploy-sandbox:
  stage: sandbox
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull-push
  extends: .upgrade
  needs:
    - job: dry-run-sandbox
  variables:
    AGENT: $NONPROD_CICD_K8S_AGENT
    TARGET_ENV: sandbox
    TARGET_NAMESPACE: sandbox
    TARGET_HOSTNAME: $DOMAIN-sandbox.np.tcw.com
    TLS_HOST_WILD: $TLS_NONPROD_HOST_WILDCARD
    TLS_HOST_LITERAL: $TLS_NONPROD_HOST_LITERAL
    TLS_SECRET: $TLS_NONPROD_SECRET_NAME
  rules:
    - if: $CI_COMMIT_BRANCH != 'main' && $ENABLE_SANDBOX == "true"

dry-run:
  stage: dry-run
  extends: .react-dry-run
  variables:
    TARGET_ENV: development
    TARGET_NAMESPACE: development
    TARGET_HOSTNAME: $DOMAIN-dev.np.tcw.com
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true"

build-dev:
  stage: development
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull
  extends: .build
  variables:
    TARGET_ENV: development
    TARGET_OUTPUT: build-dev
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_DEV == "true"

package-dev:
  stage: development
  needs:
    - job: build-dev
    - job: dry-run
  extends: .package
  variables:
    TARGET_ENV: development
    TARGET_OUTPUT: build-dev
    DOCKER_SOURCE_REF: $DEFAULT_DOCKER_SOURCE_REF
    DOCKER_SOURCE_PATH: $DEFAULT_DOCKER_SOURCE_PATH
    DOCKER_SOURCE_FILE: $DEFAULT_DOCKER_SOURCE_FILE
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_DEV == "true"

deploy-development:
  stage: development
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull-push
  needs:
    - job: dry-run
    - job: package-dev
  extends: .upgrade
  variables:
    AGENT: $NONPROD_CICD_K8S_AGENT
    TARGET_ENV: development
    TARGET_NAMESPACE: development
    TARGET_HOSTNAME: $DOMAIN-dev.np.tcw.com
    TLS_HOST_WILD: $TLS_NONPROD_HOST_WILDCARD
    TLS_HOST_LITERAL: $TLS_NONPROD_HOST_LITERAL
    TLS_SECRET: $TLS_NONPROD_SECRET_NAME
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_DEV == "true"

build-qa:
  stage: qa
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull
  extends: .build
  variables:
    TARGET_ENV: qa
    TARGET_OUTPUT: build-qa
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_QA == "true"

package-qa:
  stage: qa
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull-push
  extends: .package
  needs:
    - build-qa
  variables:
    TARGET_ENV: qa
    TARGET_OUTPUT: build-qa
    DOCKER_SOURCE_REF: $DEFAULT_DOCKER_SOURCE_REF
    DOCKER_SOURCE_PATH: $DEFAULT_DOCKER_SOURCE_PATH
    DOCKER_SOURCE_FILE: $DEFAULT_DOCKER_SOURCE_FILE
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_QA == "true"

deploy-qa:
  stage: qa
  needs:
    - job: package-qa
  extends: .upgrade
  variables:
    AGENT: $NONPROD_CICD_K8S_AGENT
    TARGET_ENV: qa
    TARGET_NAMESPACE: qa
    TARGET_HOSTNAME: $DOMAIN-qa.np.tcw.com
    TLS_HOST_WILD: $TLS_NONPROD_HOST_WILDCARD
    TLS_HOST_LITERAL: $TLS_NONPROD_HOST_LITERAL
    TLS_SECRET: $TLS_NONPROD_SECRET_NAME
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_QA == "true"

build-test:
  stage: test
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull
  extends: .build
  variables:
    TARGET_ENV: test
    TARGET_OUTPUT: build-test
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_TEST == "true"

package-test:
  stage: test
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull-push
  extends: .package
  needs:
    - build-test
  variables:
    TARGET_ENV: test
    TARGET_OUTPUT: build-test
    DOCKER_SOURCE_REF: $DEFAULT_DOCKER_SOURCE_REF
    DOCKER_SOURCE_PATH: $DEFAULT_DOCKER_SOURCE_PATH
    DOCKER_SOURCE_FILE: $DEFAULT_DOCKER_SOURCE_FILE
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_TEST == "true"

deploy-test:
  stage: test
  needs:
    - job: package-test
  extends: .upgrade
  variables:
    AGENT: $NONPROD_CICD_K8S_AGENT
    TARGET_ENV: test
    TARGET_NAMESPACE: test
    TARGET_HOSTNAME: $DOMAIN-test.np.tcw.com
    TLS_HOST_WILD: $TLS_NONPROD_HOST_WILDCARD
    TLS_HOST_LITERAL: $TLS_NONPROD_HOST_LITERAL
    TLS_SECRET: $TLS_NONPROD_SECRET_NAME
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_TEST == "true"

build-uat:
  stage: uat
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull
  extends: .build
  variables:
    TARGET_ENV: uat
    TARGET_OUTPUT: build-uat
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_UAT == "true"

package-uat:
  stage: uat
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull-push
  extends: .package
  needs:
    - build-uat
  variables:
    TARGET_ENV: uat
    TARGET_OUTPUT: build-uat
    DOCKER_SOURCE_REF: $DEFAULT_DOCKER_SOURCE_REF
    DOCKER_SOURCE_PATH: $DEFAULT_DOCKER_SOURCE_PATH
    DOCKER_SOURCE_FILE: $DEFAULT_DOCKER_SOURCE_FILE
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_UAT == "true"

deploy-uat:
  stage: uat
  needs:
    - job: package-uat
  extends: .upgrade
  variables:
    AGENT: $NONPROD_CICD_K8S_AGENT
    TARGET_ENV: uat
    TARGET_NAMESPACE: uat
    TARGET_HOSTNAME: $DOMAIN-uat.np.tcw.com
    TLS_HOST_WILD: $TLS_NONPROD_HOST_WILDCARD
    TLS_HOST_LITERAL: $TLS_NONPROD_HOST_LITERAL
    TLS_SECRET: $TLS_NONPROD_SECRET_NAME
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_UAT == "true"

build-integration:
  stage: integration
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull
  extends: .build
  variables:
    TARGET_ENV: integration
    TARGET_OUTPUT: build-integration
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_INT == "true"

package-integration:
  stage: integration
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull-push
  extends: .package
  needs:
    - build-integration
  variables:
    TARGET_ENV: integration
    TARGET_OUTPUT: build-integration
    DOCKER_SOURCE_REF: $DEFAULT_DOCKER_SOURCE_REF
    DOCKER_SOURCE_PATH: $DEFAULT_DOCKER_SOURCE_PATH
    DOCKER_SOURCE_FILE: $DEFAULT_DOCKER_SOURCE_FILE
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_INT == "true"

deploy-integration:
  stage: integration
  needs:
    - job: package-integration
  extends: .upgrade
  variables:
    AGENT: $NONPROD_CICD_K8S_AGENT
    TARGET_ENV: integration
    TARGET_NAMESPACE: integration
    TARGET_HOSTNAME: $DOMAIN-int.np.tcw.com
    TLS_HOST_WILD: $TLS_NONPROD_HOST_WILDCARD
    TLS_HOST_LITERAL: $TLS_NONPROD_HOST_LITERAL
    TLS_SECRET: $TLS_NONPROD_SECRET_NAME
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_INT == "true"

build-prod:
  stage: production
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull
  extends: .build
  variables:
    TARGET_ENV: production
    TARGET_OUTPUT: build-prod
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_PROD == "true"

package-prod:
  stage: production
  dependencies:
    - build-prod
  needs:
    - job: build-prod
  extends: .package
  variables:
    TARGET_ENV: production
    TARGET_OUTPUT: build-prod
    DOCKER_SOURCE_REF: $DEFAULT_DOCKER_SOURCE_REF
    DOCKER_SOURCE_PATH: $DEFAULT_DOCKER_SOURCE_PATH
    DOCKER_SOURCE_FILE: $DEFAULT_DOCKER_SOURCE_FILE
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_PROD == "true"

deploy-production:
  stage: production
  extends: .upgrade
  needs:
    - job: package-prod
  variables:
    AGENT: $PROD_CICD_K8S_AGENT
    TARGET_ENV: production
    TARGET_NAMESPACE: production
    TARGET_HOSTNAME: $DOMAIN.pd.tcw.com
    TLS_HOST_WILD: $TLS_PROD_HOST_WILDCARD
    TLS_HOST_LITERAL: $TLS_PROD_HOST_LITERAL
    TLS_SECRET: $TLS_PROD_SECRET_NAME
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_PROD == "true"

version:
  stage: production
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: push
  extends: .version
  needs:
    - job: deploy-production
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_PROD == "true"
tag:
  stage: production
  extends: .tag
  needs:
    - job: version
      artifacts: true
    - job: deploy-production
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true"
release:
  stage: production
  extends: .release
  needs:
    - job: version
      artifacts: true
    - job: tag
    - job: deploy-production
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_PROD == "true"

build-perf:
  stage: performance
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths: 
      - node_modules/
    policy: pull
  extends: .build
  needs:
    - job: deploy-qa
  variables:
    TARGET_ENV: performance
    TARGET_OUTPUT: build-perf
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_PERF == "true"

package-perf:
  stage: performance
  needs:
    - job: build-perf
  extends: .package
  variables:
    TARGET_ENV: performance
    TARGET_OUTPUT: build-perf
    DOCKER_SOURCE_REF: $DEFAULT_DOCKER_SOURCE_REF
    DOCKER_SOURCE_PATH: $DEFAULT_DOCKER_SOURCE_PATH
    DOCKER_SOURCE_FILE: $DEFAULT_DOCKER_SOURCE_FILE
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_PERF == "true"

deploy-perf:
  stage: performance
  extends: .upgrade
  needs:
    - job: package-perf
  variables:
    AGENT: $PROD_CICD_K8S_AGENT
    TARGET_ENV: performance
    TARGET_NAMESPACE: performance
    TARGET_HOSTNAME: $DOMAIN-perf.pd.tcw.com
    TLS_HOST_WILD: $TLS_PROD_HOST_WILDCARD
    TLS_HOST_LITERAL: $TLS_PROD_HOST_LITERAL
    TLS_SECRET: $TLS_PROD_SECRET_NAME
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_REF_PROTECTED == "true" && $ENABLE_PERF == "true"
