export const niStatusMockData = {
    processing: [
        {
            dealName: 'bofa_bsp301tcw',
            startDate: '10/14/25 - 21:44',
            tranche: 'A-R2',
            id: 'R2USFSCL00000Z',
        },
        {
            dealName: 'bofa_bsp302tcw',
            startDate: '10/14/25 - 21:44',
            tranche: 'A-R2',
            id: 'R2USFSCL00012Z',
        },
    ],
    sent: [
        {
            dealName: 'bofa_bsp303tcw',
            startDate: '10/14/25 - 21:44',
            sentToTodAt: '10/14/25 - 22:55',
            tranche: 'A-R2',
            id: 3,
        },
    ],
    completed: [
        {
            dealName: 'bofa_bsp303tcw',
            startDate: '10/14/25 - 21:44',
            sentToTodAt: '10/14/25 - 22:55',
            completedAt: '10/14/25 - 23:55',
            tranche: 'A-R2',
            id: 3,
        },
    ],
    failed: [],
};

export const mockDealDetail = {
    intexDealName: 'CITIOCP2326_RESET_022725_PX',
    bloombergDealName: null,
    dealType: 'CLO',
    collateralType: null,
    origDealBalance: '403600000.00',
    origCollatBalance: null,
    settleDate: '20251016',
    country: 'USA',
    tranches: [
        { name: 'AR', cusip: 'XXXXXXXXX', type: 'SEN_FLT' },
        { name: 'BR', cusip: 'XXXXXXXXX', type: 'MEZ_FLT' },
        { name: 'CR', cusip: 'XXXXXXXXX', type: 'MEZ_FLT' },
        { name: 'DR1', cusip: 'XXXXXXXXX', type: 'MEZ_FLT' },
        { name: 'DR2', cusip: 'XXXXXXXXX', type: 'MEZ_FLT' },
        { name: 'ER', cusip: 'XXXXXXXXX', type: 'MEZ_FLT' },
        { name: 'SUBORD', cusip: 'XXXXXXXXX', type: 'JUN_SUB' },
        { name: '#NETRATE', cusip: '', type: 'PSEUDO' },
        { name: '#NETRATEACTUAL360', cusip: '', type: 'PSEUDO' },
        { name: 'Class-DR', cusip: '', type: 'PSEUDO' },
        { name: 'TARGET_IRR1', cusip: '', type: 'PSEUDO' },
        { name: 'INTEREST_RESERVE', cusip: '', type: 'PSEUDO' },
        { name: 'SENIOR_EXPENSES', cusip: '', type: 'PSEUDO' },
        { name: 'BASE_MGMT_FEE', cusip: '', type: 'PSEUDO' },
        { name: 'SUB_MGMT_FEE', cusip: '', type: 'PSEUDO' },
        { name: 'INCENTIVE_MANAGEMENT_FEE', cusip: '', type: 'PSEUDO' },
        { name: 'FIRST_PERIOD_HAIRCUT', cusip: '', type: 'PSEUDO' },
        { name: 'COLLAT', cusip: '', type: 'PSEUDO' },
        { name: 'COLLAT_INITIAL', cusip: '', type: 'PSEUDO' },
        { name: 'COLLAT_REINVEST', cusip: '', type: 'PSEUDO' },
        { name: 'COLLAT_LOAN', cusip: '', type: 'PSEUDO' },
        { name: 'COLLAT_LOAN_NOFLOOR', cusip: '', type: 'PSEUDO' },
        { name: 'COLLAT_LOAN_FLOOR', cusip: '', type: 'PSEUDO' },
        { name: 'COLLAT_INIT_LOAN', cusip: '', type: 'PSEUDO' },
        { name: 'COLLAT_REIN_LOAN', cusip: '', type: 'PSEUDO' },
        { name: 'COLLAT_BOND', cusip: '', type: 'PSEUDO' },
        { name: 'COLLAT_INIT_BOND', cusip: '', type: 'PSEUDO' },
        {
            name: 'COLLAT_REIN_BOND',
            cusip: '',
            type: 'PSEUDO',
        },
        {
            name: 'COLLAT_BOND_FIXED',
            cusip: '',
            type: 'PSEUDO',
        },
        {
            name: 'COLLAT_BOND_FLOAT',
            cusip: '',
            type: 'PSEUDO',
        },
    ],
    assetClass: 'Fixed Income',
    assetClassCode: 'F',
    assetSubClass: 'S',
    assetType: 'CLO',
    assetTypeCode: 'CL',
};
