import { ExternalAppMetadata } from '@platform/app-registry';
import { HighestEnv, InternalAppMetadata } from './types';
import { NavbarHeader, NavbarSubHeader } from './navbarHeader.types';
import { lazy } from 'react';

export const portfolioManagementApps: (InternalAppMetadata | ExternalAppMetadata)[] = [
    {
        header: NavbarHeader.PortfolioManagement,
        subHeader: NavbarSubHeader.AladdinPortfolioManagement,
        type: 'external',
        title: 'TOD',
        devUrl: 'https://tod-dev.np.tcw.com/',
        qaUrl: 'https://tod-qa.np.tcw.com/',
        prodUrl: 'https://tod.pd.tcw.com/',
        newTab: true,
        disabled: false,
        env: HighestEnv.prod
    },
    {
        header: NavbarHeader.PortfolioManagement,
        subHeader: NavbarSubHeader.IM_Agency,
        type: 'external',
        title: 'ACSE',
        sandboxUrl: 'https://agency-allocator-qa.np.tcw.com/',
        devUrl: 'https://agency-allocator-qa.np.tcw.com/',
        qaUrl: 'https://agency-allocator-qa.np.tcw.com/',
        prodUrl: 'https://agency-allocator.pd.tcw.com/',
        newTab: true,
        disabled: false,
        env: HighestEnv.prod
    },
    {
        header: NavbarHeader.PortfolioManagement,
        subHeader: NavbarSubHeader.IM_Agency,
        type: 'external',
        title: 'Slicer',
        sandboxUrl: 'https://sector-summary-webapp-qa.np.tcw.com/agency/slicer',
        devUrl: 'https://sector-summary-webapp-qa.np.tcw.com/agency/slicer',
        qaUrl: 'https://sector-summary-webapp-qa.np.tcw.com/agency/slicer',
        prodUrl: 'https://sector-summary-webapp.pd.tcw.com/agency/slicer',
        newTab: true,
        disabled: false,
        env: HighestEnv.prod
    },
    {
        header: NavbarHeader.PortfolioManagement,
        subHeader: NavbarSubHeader.IM_Credit,
        type: 'external',
        title: 'Home Page',
        sandboxUrl: 'https://sector-summary-webapp-qa.np.tcw.com/credit/home',
        devUrl: 'https://sector-summary-webapp-qa.np.tcw.com/credit/home',
        qaUrl: 'https://sector-summary-webapp-qa.np.tcw.com/credit/home',
        prodUrl: 'https://sector-summary-webapp.pd.tcw.com/credit/home',
        newTab: true,
        disabled: false,
        env: HighestEnv.prod
    },
    {
        header: NavbarHeader.PortfolioManagement,
        subHeader: NavbarSubHeader.IM_Rates,
        type: 'external',
        title: 'Order Hedge',
        sandboxUrl: 'https://duration-mgmt-app-qa.np.tcw.com/',
        devUrl: 'https://duration-mgmt-app-qa.np.tcw.com/',
        qaUrl: 'https://duration-mgmt-app-qa.np.tcw.com/',
        prodUrl: 'https://duration-mgmt-app.pd.tcw.com/',
        newTab: true,
        disabled: false,
        env: HighestEnv.prod
    },
    {
        header: NavbarHeader.PortfolioManagement,
        subHeader: NavbarSubHeader.IM_Rates,
        type: 'external',
        title: 'Duration Monitor',
        sandboxUrl: 'https://irmqa.corp.tcw.com/duration-monitoring?desktype=rates',
        devUrl: 'https://irmqa.corp.tcw.com/duration-monitoring?desktype=rates',
        qaUrl: 'https://irmqa.corp.tcw.com/duration-monitoring?desktype=rates',
        prodUrl: 'https://irm.corp.tcw.com/duration-monitoring?desktype=rates',
        newTab: true,
        disabled: false,
        env: HighestEnv.prod
    },
    {
        header: NavbarHeader.PortfolioManagement,
        subHeader: NavbarSubHeader.IM_Rates,
        type: 'external',
        title: 'Home Page ',
        sandboxUrl: 'https://sector-summary-webapp-qa.np.tcw.com/rates/home',
        devUrl: 'https://sector-summary-webapp-qa.np.tcw.com/rates/home',
        qaUrl: 'https://sector-summary-webapp-qa.np.tcw.com/rates/home',
        prodUrl: 'https://sector-summary-webapp.pd.tcw.com/rates/home',
        newTab: true,
        disabled: false,
        env: HighestEnv.prod
    },
    {
        header: NavbarHeader.PortfolioManagement,
        subHeader: NavbarSubHeader.InvestmentManagementSolutions,
        type: 'external',
        title: 'IM (Aladdin Integrated Tools)',
        sandboxUrl: 'http://localhost:5406/tools/iralaunchpad/?tdenv=qa&mode=aladdin',
        devUrl: 'http://localhost:5406/tools/iralaunchpad/?tdenv=qa&mode=aladdin',
        qaUrl: 'http://localhost:5406/tools/iralaunchpad/?tdenv=qa&mode=aladdin',
        prodUrl: 'http://localhost:5406/tools/iralaunchpad/?tdenv=prod&mode=aladdin',
        newTab: false,
        disabled: false,
        env: HighestEnv.prod
    },
    {
        header: NavbarHeader.PortfolioManagement,
        subHeader: NavbarSubHeader.InvestmentManagementSolutions,
        type: 'external',
        title: 'IM (Retired Tools)',
        sandboxUrl: 'http://localhost:5406/tools/iralaunchpad/?tdenv=qa&mode=legacy',
        devUrl: 'http://localhost:5406/tools/iralaunchpad/?tdenv=qa&mode=legacy',
        qaUrl: 'http://localhost:5406/tools/iralaunchpad/?tdenv=qa&mode=legacy',
        prodUrl: 'http://localhost:5406/tools/iralaunchpad/?tdenv=prod&mode=legacy',
        newTab: false,
        disabled: false,
        env: HighestEnv.prod,
    },
    {
        type: 'internal',
        header: NavbarHeader.PortfolioManagement,
        subHeader: NavbarSubHeader.AladdinPortfolioManagement,
        id: 'tdm',
        name: 'TDM',
        title: 'Security Setup Dashboard',
        env: HighestEnv.prod,
        path: '/iod/tdm/*',
        team: 'IOD',
        component: lazy(() => import('@IOD/tdm/src/App')),
        description: '',
    },
    {
        type: 'internal',
        header: NavbarHeader.PortfolioManagement,
        subHeader: NavbarSubHeader.AladdinPortfolioManagement,
        id: 'bskt-composition',
        name: 'bskt-composition',
        title: 'Etf Basket Negotiation',
        env: HighestEnv.prod,
        path: '/IOD/bskt-composition/',
        team: 'IOD',
        component: lazy(() => import('@IOD/bskt-composition/src/App')),
        description: '',
    },
    {
        header: NavbarHeader.PortfolioManagement,  
        subHeader: NavbarSubHeader.Equity,  
        type: 'internal',  
        id: '@iod/ebc/maintenance',  
        name: 'IOD-EBC-Maintenance',  
        title: 'Budget - Maintenance',  
        path: '/equity/budget/maintenance',  
        team: 'IOD',  
        env: HighestEnv.prod,            
        component: lazy(() => import('@iod/equity-budget-commission/src/pages/budget-maintenance-page'))       
    },
    {
        header: NavbarHeader.PortfolioManagement,  
        subHeader: NavbarSubHeader.Equity,  
        type: 'internal',  
        id: '@iod/ebc/softdollar',  
        name: 'IOD-EBC-Softdollar',  
        title: 'Budget - Soft Dollar Budget',  
        path: '/equity/budget/softdollarbudget',  
        team: 'IOD',                  
        env: HighestEnv.prod,            
        component: lazy(() => import('@iod/equity-budget-commission/src/pages/budget-soft-dollar-page'))       
    },    
    {
        header: NavbarHeader.PortfolioManagement,  
        subHeader: NavbarSubHeader.Equity,  
        type: 'internal',  
        id: '@iod/ebc/researchbudget',  
        name: 'IOD-EBC-ResearchBudget',  
        title: 'Budget - Research Budget',  
        path: '/equity/budget/researchbudget',  
        team: 'IOD',                  
        env: HighestEnv.prod,            
        component: lazy(() => import('@iod/equity-budget-commission/src/pages/budget-research-budget-page'))       
    },
    {
        header: NavbarHeader.PortfolioManagement,  
        subHeader: NavbarSubHeader.Equity,  
        type: 'internal',  
        id: '@iod/ebc/annualresearchbudget',  
        name: 'IOD-EBC-AnnualResearchBudget',  
        title: 'Budget - Create Annual Research Budget',  
        path: '/equity/budget/annualresearchbudget',  
        team: 'IOD',                  
        env: HighestEnv.prod,            
        component: lazy(() => import('@iod/equity-budget-commission/src/pages/annual-research-budget-page'))       
    },
    {
        header: NavbarHeader.PortfolioManagement,  
        subHeader: NavbarSubHeader.Equity,  
        type: 'internal',  
        id: '@iod/ebc/combinedbudget',  
        name: 'IOD-EBC-CombinedBudget',  
        title: 'Commission - Combined Budgets', 
        path: '/equity/commission/combinedbudget',  
        team: 'IOD',                  
        env: HighestEnv.prod,            
        component: lazy(() => import('@iod/equity-budget-commission/src/pages/commission-combinedbudget-page'))       
    },
    {
        header: NavbarHeader.PortfolioManagement,  
        subHeader: NavbarSubHeader.Equity,  
        type: 'internal',  
        id: '@iod/ebc/commissiontrades',  
        name: 'IOD-EBC-CombinedBudget',  
        title: 'Commission - Trades',  
        path: '/equity/commission/trades',  
        team: 'IOD',                  
        env: HighestEnv.prod,            
        component: lazy(() => import('@iod/equity-budget-commission/src/pages/commission-trade-page'))       
    },
    {
        header: NavbarHeader.PortfolioManagement,  
        subHeader: NavbarSubHeader.Equity,  
        type: 'internal',  
        id: '@iod/ebc/csamonthlycommission',  
        name: 'IOD-EBC-CSAMonthly',  
        title: 'Commission - CSA Monthly Commission',  
        path: '/equity/commission/csa-monthly',  
        team: 'IOD',
        env: HighestEnv.prod,            
        component: lazy(() => import('@iod/equity-budget-commission/src/pages/commission-csa-monthly-page'))
    },
    {
        header: NavbarHeader.PortfolioManagement,  
        subHeader: NavbarSubHeader.Equity,  
        type: 'internal',  
        id: '@iod/ebc/reports',  
        name: 'IOD-EBC-reports',  
        title: 'Reports',  
        path: '/equity/reports',  
        team: 'IOD',                  
        env: HighestEnv.prod,            
        component: lazy(() => import('@iod/equity-budget-commission/src/pages/report-dashboard'))       
    },
    {
        type: 'internal',
        header: NavbarHeader.PortfolioManagement,
        subHeader: NavbarSubHeader.IM_Rates,
        id: 'pfa',
        name: 'pfa',
        title: 'Drift Report',
        env: HighestEnv.prod,
        path: '/IOD/pfa/',
        team: 'IOD',
        component: lazy(() => import('@IOD/pfa/src/App')),
        description: '',
        hideFooter: true
    },
    // PLOP_INJECT_APP
]
