import { RowDataType } from './types';

export const MAIN_GRID_FIELDS: RowDataType[] = [
    { key: 'assetId', label: 'Asset ID' },
    { key: 'riskDate', label: 'Risk Date' },
    { key: 'currency', label: 'Currency' },
    { key: 'assetIdType', label: 'Asset Id Type' },
    { key: 'curveType', label: 'Curve Type' },
    { key: 'oad', label: 'OAD' },
    { key: 'modelOad', label: 'Model OAD' },
    { key: 'modDur', label: 'Mod Dur' },
    { key: 'modDurToWorst', label: 'Mod Dur To Worst' },
    { key: 'volDur', label: 'Vol Dur' },
    { key: 'inflDuration', label: 'Infl Duration' },
    { key: 'realDuration', label: 'Real Duration' },
    { key: 'oac', label: 'OAC' },
    { key: 'oas', label: 'OAS' },
    { key: 'oas1', label: 'OAS1' },
    { key: 'price', label: 'Price' },
    { key: 'spdDur', label: 'Spd Dur' },
    { key: 'spreadToWorst', label: 'Spread To Worst' },
    { key: 'wal', label: 'WAL' },
    { key: 'walToWorst', label: 'WAL To Worst' },
    { key: 'yieldToMaturity', label: 'Yield To Maturity' },
    { key: 'yieldToWorst', label: 'Yield To Worst' },
    { key: 'zvWal', label: 'ZV WAL' },
    { key: 'zvYield', label: 'ZV Yield' },
    { key: 'staticYield', label: 'Static Yield' },
    { key: 'modelOad', label: 'Model OAD' },
    { key: 'modelOac', label: 'Model OAC' },
    { key: 'oav', label: 'OAV' },
];

export const KRD_FIELDS: RowDataType[] = [
    { key: 'sprdOffWal', label: 'Sprd Off Wal' },
    { key: 'volatility', label: 'Volatility' },
    { key: 'volConv', label: 'Vol Conv' },
    { key: 'realYield', label: 'Real Yield' },
    { key: 'rorCbe', label: 'ROR CBE' },
    { key: 'krdBenchCusip', label: 'KRD Bench Cusip' },
    { key: 'krdSource', label: 'KRD Source' },
    { key: 'krdDate', label: 'KRD Date' },
    { key: 'krd3M', label: 'KRD 3M' },
    { key: 'krd1Y', label: 'KRD 1Y' },
    { key: 'krd2Y', label: 'KRD 2Y' },
    { key: 'krd3Y', label: 'KRD 3Y' },
    { key: 'krd5Y', label: 'KRD 5Y' },
    { key: 'krd7Y', label: 'KRD 7Y' },
    { key: 'krd10Y', label: 'KRD 10Y' },
    { key: 'krd15Y', label: 'KRD 15Y' },
    { key: 'krd20Y', label: 'KRD 20Y' },
    { key: 'krd25Y', label: 'KRD 25Y' },
    { key: 'krd30Y', label: 'KRD 30Y' },
    { key: 'krd40Y', label: 'KRD 40Y' },
    { key: 'krd50Y', label: 'KRD 50Y' },
    { key: 'fileProcessingStatus', label: 'File Processing Status', isEditingDisabled: true },
    { key: 'brsFileName', label: 'BRS File Name', isEditingDisabled: true },
    { key: 'createdBy', label: 'Created By', isEditingDisabled: true },
    { key: 'createdDate', label: 'Created Date', isEditingDisabled: true },
    { key: 'lastModifiedBy', label: 'Last Modified By', isEditingDisabled: true },
    { key: 'lastModifiedDate', label: 'Last Modified Date', isEditingDisabled: true },
];
